import Head from 'next/head';

export default function HeadInfo() {
    return (
        <Head>
        <title>My For Funsies Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
}